### ISSUE TITLE
rz_thumbnail_gallery: new gallery modes fail when language in root module is set to german

### ISSUE THREAD

**Issue by jschroeter** [rukzuk/rukzuk#11]
https://github.com/rukzuk/rukzuk/blob/6d24c41ebc292af3542a6f300a5b11819da62fac/app/sets/rukzuk/rz_core/modules/rz_thumbnail_gallery/module/rz_thumbnail_gallery.php#L72

When setting the language in the root module to german, PHP prints the `flex-grow` with a comma (1,123) instead of dot (1.123). At least in Chrome the images are not visible since it's an invalid value.

**Comment by carlos22** [comment]
The safest solution might be something like:
`$imageRatio = number_format($imageRatio, 4, '.', '');`

**Comment by sebastianroller** [comment]
You're absolutely right, thank you for your feedback!

**Comment by carlos22** [comment]
fixed in 51c59a8c32b3f6d6f4613de4ff49b4612a8d4d9a
