### ISSUE TITLE
Docker: Unable to send E-Mail from Instance

### ISSUE THREAD

**Issue by frankziski** [rukzuk/rukzuk#14]
I successfully run a container with the rukzuk image on my webserver. 

The ony thing that wont work is sending e-mails. Whenever i try to send the passwort mail to a new user it says "Unable to send mail. "

Environmental Variables for the SMTP Server are set correct, as docker says..

![image](https://user-images.githubusercontent.com/37303044/37293321-389ac382-2613-11e8-8f56-9ab4b5970e37.png)

![image](https://user-images.githubusercontent.com/37303044/37293384-683f8da2-2613-11e8-826d-6a427cf789d0.png)

**Comment by carlos22** [comment]
To use gmail you need to enable something like "unsecure imap/smtp access" inside of the gmail settings. Otherwise Gmail requires you to do OAuth before connecting to their SMTP server. Some E-Mail Clients support that, for others you need to change the settings.

**Comment by frankziski** [comment]
This does not solve the problem. I activated IMAP inside GMAIL and allowed unsecure apps to connect to my account. I haven´t found any other setting to apply:

![image](https://user-images.githubusercontent.com/37303044/37328508-bec2a196-269a-11e8-9c30-6cbd3bdbe17f.png)

![image](https://user-images.githubusercontent.com/37303044/37328518-c79399ce-269a-11e8-9dcc-0f5ee763cf3a.png)

**Comment by frankziski** [comment]
Is there any solution? without a proper Mail-Configuration i cant use rukzuk on my server..

**Comment by carlos22** [comment]
Did you test any other SMTP server? I did use it a while ago with my own SMTP server and it worked. You might take a look at the logs of the nullmailer or try to send mails from the bash inside of the container (sendmail command).

Am 14. März 2018 12:49:05 MEZ schrieb frankziski <notifications@github.com>:

**Comment by frankziski** [comment]
I changed the mail config to my own server. Now the Error Message in rukzuk is different: "Time Limit Exceeded"

The Logs are empty. However with the gmail-config I got some errors from sendmail. But i wuld prefer to use my own smtp server. Is this some security from the provider? I have a virtual server running with my domain.

**Comment by carlos22** [comment]
Hmm, not sure. Will try to get it working with my server and tell you if it works....

**Comment by frankziski** [comment]
I fixed the problem now with the help of an expert.

First of all: We only got it work with the demo installation image rukzuk/rukzuk, not with the one provided for a clean installation. 

The Problem with sending mails was because rukzuk said that the hostname is localhost. So the mailserver rejected the mails because he is the localhost.

Here is what we did:

1. check running containers:
`docker ps`

2. enter the container:
`docker exec -ti <CONTAINERNAME> /bin/bash`

3. install sSMTP for this container:
`apt update`
`apt install ssmtp`

4. edit the ssmtp.conf:
`nano /etc/ssmtp/ssmtp.conf`

` root=<YOURMAIL@HOST.COM>
mailhub=<MAILSERVER:PORT>
rewriteDomain=<YOUR-DOMAIN>
# The full hostname -> e.g. "rukzuk-docker-host"
hostname=<HOSTNAME>
FromLineOverride=YES
AuthUser=<USER@DOAMIN.TLD>
AuthPass=<PASSWORD>
UseTLS=YES `

5. Edit the Revalias
`nano /etc/ssmtp/revaliases`
`www-data:<YOURMAIL@HOST.COM>`

6. Check the Mail Log for Testing
`tailf /var/log/mail.log`

7. With the use of those settings you can run the container without sending the parameters. (Obviously as first step...)

`docker run --name rukzuk -e "CMS_URL=http://$(hostname)" -d -p 80:80 rukzuk/rukzuk`

**Comment by carlos22** [comment]
> not with the one provided for a clean installation.
What should that be? the rukzuk/rukzuk is just the published image on docker hub - if you use docker build it should create the same image (as it uses the same Dockerfile).

That is not an solution, as you install your on Sendmail like fake-MTA (ssmtp). We used msmtp-mta (see: https://github.com/rukzuk/rukzuk/blob/master/docker/Dockerfile#L33 ). We configure this msmtp-mta at each start in the init.sh script (see: https://github.com/rukzuk/rukzuk/blob/master/docker/init.sh ) with the provided ENV parameters. 

SSMTP might be more compatible with the SMTP server config you use, but replacing the MTA should not be done after the container is build (you should never change anything AFTER the build). So editing the Dockerfile is the way to go... 

But I'm still not convinced that it is the fault of the msmtp tool...

**Comment by frankziski** [comment]
Well there is also the "rukzuk_image" which can be used. But with that one it didnt work.

Well, all i can say is, that with the provided solution and the parameters given to the run command it didnt work. Not with my own server and not with gmail. All i got was a timeout.

My friend, who installed this solution for me, said it was a problem with the hostname. 

Anyway: I am happy with the way this works now. If you have any more practicle solution i would be happy to see that. I really like rukzuk and i want to improve it by writing own modules and stuff...

**Comment by carlos22** [comment]
> Well there is also the "rukzuk_image" which can be used. But with that one it didnt work.

The rukzuk_image is build with `docker build .` locally. the rukzuk/rukzuk image is downloaded from docker hub. There is no test or official one. Maybe the docs are not very clear at this point?
It might not work if you send a mail from text@example.com but the mailserver only is allowed to send from mail@mycustomdomain.de and refuses all other domains in the "From:" field. But in the case of gmail the at least used to rewrite the From: headers. The SSMTP seems to do the same as stated in ` FromLineOverride=YES` - that is indeed a good idea as rukuk sends the mail "From:" the configured email address.

**Comment by frankziski** [comment]
Yeah maybe the docs are not clear at this point. I tried many possibilities with the mail config for the run -e parameters but none have worked.

But i am very happy now. Thanks for the good work putting rukzuk in a docker image. Its awesome :)
