### ISSUE TITLE
CI: Sunsetting CircleCI 1.0 on August 31st, 2018

### ISSUE THREAD

**Issue by carlos22** [rukzuk/rukzuk#19]
This requires a migration to 2.0 or any other service for automated builds.

**Comment by carlos22** [comment]
Docs: https://circleci.com/sunset1-0/

**Comment by carlos22** [comment]
Auto-translated config: https://gist.github.com/carlos22/37b0dbbfef453fa774b7855231a6afb4

**Comment by trunneml** [comment]
@carlos22: I will look at it.

**Comment by carlos22** [comment]
I think we should consider to run tests with both php 5.x and php 7.x.

**Comment by carlos22** [comment]
Travis supports Dockerfiles, this would simplify CI as many of the Dockerfile could be reused. Example: https://github.com/phpv8/v8js/commit/ddfb9ec012d044ee020fe7654f6f225d8c373c91
This example also shows how to test against different php versions (and different libv8 versions, which is less important for us but still nice to adapt).

**Comment by carlos22** [comment]
This is rather urgent right now. Only 6 weeks to go!

**Comment by trunneml** [comment]
The biggest problem seems to be the v8js php extension. The circleci2.0 is newer then the circleci1.0 trusty image. That's a problem. Any ideas to replace quickly v8js?

**Comment by carlos22** [comment]
Is it xenial?

**Comment by trunneml** [comment]
Nope g++ is newer and throws more warnings. I "fixed" it by disabling all compiler warnings.

**Comment by carlos22** [comment]
Good work. Well the v8js version 0.1.3 is very old, we might use an newer version. But this always requires the check of the system v8 version. Is the image provided by circleci still 14.04?

**Comment by trunneml** [comment]
The CircleCi docker image is based on the official php docker image (debian stretch). There are two reasons for version 0.1.3. The latest v8js Version that supports PHP5.6 is afaik 0.1.3 [1]. The second problem is that newer versions of PHP-v8js need a newer libv8 version, but debian still only includes 3.14. [2] [3]

[1] https://blog.xenokore.com/how-to-install-v8js-for-php-on-linux/
[2] https://stackoverflow.com/questions/29229149/how-to-install-v8js-on-php5-5
[3] https://packages.debian.org/search?keywords=libv8

**Comment by carlos22** [comment]
That is a big problem with debian, I think ubuntu 16.04 ships newer versions, but they are also very much outdated. I think the current solution is good and the rukzuk.com production platform runs still 14.04 i thnik... 

We might use an ubuntu image and ppa packages of v8 and the latest phpv8js version in the php7 branch later. Or even use our own image (based on the Dockerfile in the repo), I think this is also possible now?

**Comment by carlos22** [comment]
Agreed. I think the vagrant vm is already based on the dev dockerfile (and that is also there): https://github.com/rukzuk/rukzuk/blob/master/Vagrantfile#L13

But not sure how well both works (not used it for a long time).

**Comment by trunneml** [comment]
@carlos22 What are the artifacts from these build steps:

      - run: npm install
      - run: grunt composer:dev:install
      - run: grunt composer:production:install
      - run:
          command: npm install
          working_directory: app/sets/rukzuk

We need to add the artifacts with persist_to_workspace in circleci2.0 so that later jobs like test and deploy can use them.

**Comment by carlos22** [comment]
They create 'node_modules' and 'vendor' folders. 

Am 26. August 2018 10:56:59 MESZ schrieb Michael Trunner <notifications@github.com>:

**Comment by trunneml** [comment]
So the build is running (when circleci has no DNS problems). Only thing that is not working is the tag trigger. I try to fix that in the next days.

**Comment by trunneml** [comment]
Tag building is working. I will cleanup the branche and merge it tomorrow.

**Comment by carlos22** [comment]
Looks very good! :+1:

**Comment by trunneml** [comment]
I rebased the branch and created a pull request  #25

**Comment by trunneml** [comment]
#25 is merged
