### ISSUE TITLE
... returned a non-zero code: 100 / Zudem alles veraltet!

### ISSUE THREAD

**Issue by user18x** [rukzuk/rukzuk#32]
Was ist denn das für eine Scheiße?!
Das original Dockerfile verwendet um ein Image zu erstellen, doch es kommt:
`Step 4/33 : RUN apt-get update  &&       apt-get dist-upgrade -y --no-install-recommends
---> Running in efe751cd5267
E: Opening configuration file /etc/apt/apr.conf.d/01autoremove - ifstream::ifream (13: Permission denied)
The command 'bin/sh -c apt-get update  &&     apt-get dist-upgrade -y --no-install-recommends' returned a non-zero code: 100`

Euere verwendeten PHP-Dateien etc. sind zudem alle veraltet!
Seid ihr nicht in der Lage alles aktuell zu halten?

**Comment by carlos22** [comment]
Lol. Wir setzen die docker images nicht produktiv ein. In der Lage wäre man sicher...

Es gibt ein PR für laufende dockerfiles. Den kannst du ja nutzen...

Es gibt auch ein php7 branch mit dockerfiles für php 7 - die sind allerdings auch nicht mehr so frisch. 



Am 27. April 2019 13:35:25 MESZ schrieb user18x <notifications@github.com>:

**Comment by user18x** [comment]
Was meinst du mit PR? **P**ull **R**equest?
Link?

Ich würde das Docker Image schon gerne "produktiv" einsetzen.
Wenn es also möglich wäre...
Updates erwünscht!

**Comment by carlos22** [comment]
Äh ja klar PR = Pull Request: https://github.com/rukzuk/rukzuk/pull/29
Das ganze ist zwar open source, heißt aber ja nicht das jemand für dich die Arbeit macht ;-)
Wenn du einfach nur nutzen willst dann kannst du ja auch die hosted variante nutzen: https://rukzuk.com/de/Preise/
Oder es von jemandem hosten lassen. Mit deiner brechstangen forderungs attitüde sammelst du schon mal keine Sympathiepunkte.

**Comment by user18x** [comment]
Danke, aber ich würde es gerne selbst **lokal hosten** und nutzen (keine Kosten ;-) )!

Den PR habe ich mir angeschaut. Allerdings funktioniert auch dieses Dockerfile nicht! :-(

Ich bin ja der Meinung, wenn man der Öffenlichkeit etwas anbietet, dann sollte das nicht veraltet sein. ;-)
Das obige hast du vll. auch nur falsch verstanden. :-S

**Comment by carlos22** [comment]
> Ich bin ja der Meinung, wenn man der Öffenlichkeit etwas anbietet, dann sollte das nicht veraltet sein. ;-)
Naja das kannst du ja so sehen, aber github ist ja kein Wunschkonzert. 

Keine Kosten gibts nicht, kosetet immer und wenns nur die eigene Zeit ist ;-)

> Den PR habe ich mir angeschaut. Allerdings funktioniert auch dieses Dockerfile nicht! :-(

Möglich ich nutze es selbst nicht. Ich hoste das zwar selber, aber ohne docker (weil es die Sache nur bedingt einfacher macht). Aber es baut bei mir zumindest mal das image mit dem PR. Daher hab ich den PR mal gemerged. Anleitung zum bauen des images findet sich in: https://github.com/rukzuk/rukzuk/blob/master/docker/README.md

Rein vom deinem Wissensstand her würde ich dir vom selber hosten abraten. Vor allem wenn du glaubst das es einfach funktioniert und upstream (also von uns) gewartet wird. Das ist bei der wenigsten software so, vor allem nicht wenn es so ein kleines Team ist!

**Comment by kocher** [comment]
Hallo Carlos,

den PR bitte rückgängig machen. php-v8js ist für eine andere Version von PHP und kann deshalb nicht geladen werden:

`PHP Warning:  PHP Startup: v8js: Unable to initialize module\nModule compiled with module API=20121212\nPHP    compiled with module API=20131226\nThese options need to match\n in Unknown on line 0`

Das aktuelle Image ist leider so nicht benutzbar - bei mir wird keinerlei CSS angezeigt, vermutlich gehen auch andere Dinge nicht.

**Comment by carlos22** [comment]
Hmm, hat bei mir eigentlich funktioniert. Da war ja eine neue Version mit dabei im PR.

**Comment by kocher** [comment]
Ja, Bauen funktioniert, Login usw geht, allerdings CSS z.B. überhaupt nicht.

**Comment by carlos22** [comment]
Lief bei mir. Sonst hätte ich ja nicht gemerged ;-). Sonst mal @djnews24 fragen.

**Comment by djnews24** [comment]
Grundsätzlich hat es zum Zeitpunkt des PRs funktioniert. Sorry aber mit diesem Tonfall gibt es auch von meiner Seite aus keinen Support. Opensource = Feel free to fix.

**Comment by djnews24** [comment]
@kocher: ich guck mir das die Tage an.

**Comment by djnews24** [comment]
@kocher schau dir mal https://github.com/rukzuk/rukzuk/pull/33 an. sollte damit behoben sein

**Comment by carlos22** [comment]
@kocher bitte neues issue machen falls du etwas findest. Hier mache ich mal zu.
